// FileInfoUI.java
// Gayathri Singh, March 2008, gayathri@byteblend.com

/* The FileInfoUI class provides a GUI frontend for the FileInfo class.
 
   Usage: 
     java -cp c:\jinvoke\jinvoke.jar;. jinvoke.win32demos.fileinfo.FileInfoUI  [ file-path ]
*/


package jinvoke.win32demos.fileinfo;

import java.awt.event.ActionListener;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.UIManager;

public class FileInfoUI extends javax.swing.JFrame {
    JFileChooser fc;
    /** Creates new form GetFileInfoUI */
    public FileInfoUI(String filepath) {
        initComponents();
        txtFieldSource.setText(filepath);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        displayFileInfo();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFieldSource = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        btnGetFileInfo = new javax.swing.JButton();
        lblFileInfo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblFileImage = new javax.swing.JLabel();
        lblFileName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFileType = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCompressedSize = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        chkHidden = new javax.swing.JCheckBox();
        lblVolumeSerialNum = new javax.swing.JLabel();
        lblNumLinks = new javax.swing.JLabel();
        lblUniqueIdentifier = new javax.swing.JLabel();
        lblCreated = new javax.swing.JLabel();
        lblAccessed = new javax.swing.JLabel();
        lblModified = new javax.swing.JLabel();
        chkSystem = new javax.swing.JCheckBox();
        chkArchive = new javax.swing.JCheckBox();
        chkCompressed = new javax.swing.JCheckBox();
        chkTemporary = new javax.swing.JCheckBox();
        chkReadOnly = new javax.swing.JCheckBox();
        btnClose = new javax.swing.JButton();
        btnClose.addActionListener(new ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		System.exit(0);
        	}
        });
        
        lblFileSize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("File Information"); // NOI18N
        setResizable(false);

        jLabel1.setText("Select a File:");

        
        btnBrowse.setText("...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnGetFileInfo.setText("Get File Information");
        btnGetFileInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetFileInfoActionPerformed(evt);
            }
        });

        lblFileInfo.setText("File Information:");

        lblFileName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel2.setText("Type:");

        jLabel3.setText("Size:");

        jLabel5.setText("Compressed Size:");

        jLabel6.setText("Volume Serial Number:");

        jLabel7.setText("Number of Links to File:");

        jLabel8.setText("File Unique Identifier:");

        jLabel9.setText("Created:");

        jLabel10.setText("Accessed:");

        jLabel11.setText("Modified:");

        jLabel12.setText("Attributes:");

        chkHidden.setText("Hidden");
        chkHidden.setOpaque(false);

        chkSystem.setText("System");
        chkSystem.setOpaque(false);

        chkArchive.setText("Archive");
        chkArchive.setOpaque(false);

        chkCompressed.setText("Compressed");
        chkCompressed.setOpaque(false);

        chkTemporary.setText("Temporary");
        chkTemporary.setOpaque(false);
        chkTemporary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTemporaryActionPerformed(evt);
            }
        });

        chkReadOnly.setText("Read-Only");
        chkReadOnly.setOpaque(false);

        btnClose.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkArchive)
                    .addComponent(chkTemporary)
                    .addComponent(chkHidden))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkSystem)
                    .addComponent(chkReadOnly)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnClose)
                        .addComponent(chkCompressed)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGetFileInfo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldSource, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(297, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFileInfo)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(lblFileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompressedSize)
                    .addComponent(lblFileType)
                    .addComponent(lblAccessed)
                    .addComponent(lblCreated)
                    .addComponent(lblUniqueIdentifier)
                    .addComponent(lblNumLinks)
                    .addComponent(lblVolumeSerialNum)
                    .addComponent(lblModified)
                    .addComponent(lblFileSize)
                    .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFieldSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGetFileInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFileInfo)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFileType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFileSize)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblCompressedSize))
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblVolumeSerialNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblNumLinks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblUniqueIdentifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblCreated))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblAccessed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblModified))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(chkHidden)
                    .addComponent(chkSystem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkArchive)
                    .addComponent(chkCompressed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTemporary)
                    .addComponent(chkReadOnly))
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, lblFileName});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        //Set up the file chooser.
        if (fc == null) 
                fc = new JFileChooser();
        //Show it.
        int returnVal = fc.showDialog(this, "Select File");
        //Process the results.
        if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                txtFieldSource.setText(file.getPath());
               // getFileInformation(file.getPath());
        }
        //Reset the file chooser for the next time it's shown.
        fc.setSelectedFile(null);
}//GEN-LAST:event_btnBrowseActionPerformed

    private void chkTemporaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTemporaryActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkTemporaryActionPerformed

    private void btnGetFileInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetFileInfoActionPerformed
    	displayFileInfo();
    }//GEN-LAST:event_btnGetFileInfoActionPerformed
    
    private void displayFileInfo() {
		FileInfo fileInfo = new FileInfo(txtFieldSource.getText());
		lblFileImage.setIcon(fileInfo.icon);
		lblFileName.setText(fileInfo.fileName);
		lblFileType.setText(fileInfo.typeName);
		chkArchive.setSelected(fileInfo.isArchive);
		chkCompressed.setSelected(fileInfo.isCompressed);
		if (fileInfo.isCompressed) 
			lblCompressedSize.setText(fileInfo.compressedFileSize + " bytes");
		else
			lblCompressedSize.setText("File is not compressed");
		chkHidden.setSelected(fileInfo.isHidden);
		chkReadOnly.setSelected(fileInfo.isReadOnly);
		chkSystem.setSelected(fileInfo.isSystemFile);
		chkTemporary.setSelected(fileInfo.isTempFile);
		lblCreated.setText(fileInfo.createdTime.toString());
		lblAccessed.setText(fileInfo.accessedTime.toString());
		lblModified.setText(fileInfo.modifiedTime.toString());
		
		lblVolumeSerialNum.setText(Integer.toHexString(fileInfo.volumeSerialNumber));
		lblFileSize.setText(fileInfo.fileSize + " bytes");
		lblNumLinks.setText(fileInfo.numLinks+"");
		lblUniqueIdentifier.setText(Long.toHexString(fileInfo.uniqueIdentifier));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {
                	String path = "C:\\Windows\\Notepad.exe";
                	if (args.length == 1)
                		path = args[0];
                	
                	FileInfoUI fileInfoUI = new FileInfoUI(path);
                	fileInfoUI.setVisible(true);
                }
            });
        } catch (Exception ex) {
            Logger.getLogger(FileInfoUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGetFileInfo;
    public javax.swing.JCheckBox chkArchive;
    public javax.swing.JCheckBox chkCompressed;
    public javax.swing.JCheckBox chkHidden;
    public javax.swing.JCheckBox chkReadOnly;
    public javax.swing.JCheckBox chkSystem;
    public javax.swing.JCheckBox chkTemporary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JLabel lblAccessed;
    public javax.swing.JLabel lblCompressedSize;
    public javax.swing.JLabel lblCreated;
    public javax.swing.JLabel lblFileImage;
    private javax.swing.JLabel lblFileInfo;
    public javax.swing.JLabel lblFileName;
    public javax.swing.JLabel lblFileSize;
    public javax.swing.JLabel lblFileType;
    public javax.swing.JLabel lblModified;
    public javax.swing.JLabel lblNumLinks;
    public javax.swing.JLabel lblUniqueIdentifier;
    public javax.swing.JLabel lblVolumeSerialNum;
    private javax.swing.JTextField txtFieldSource;
    // End of variables declaration//GEN-END:variables
    
}
