// FileOperationsUI.java
// Gayathri Singh, March 2008, gayathri@byteblend.com

/* This class provides the GUI frontend for the FileOperations class, which 
   performs file operations such as copy, move or delete using
   the Shell32.SHFileOperation API. 
   
   Usage: 
     java -cp c:\jinvoke\jinvoke.jar;. jinvoke.win32demos.fileoperations.FileOperations
*/

package jinvoke.win32demos.fileoperations;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.UIManager;

public class FileOperationsUI extends javax.swing.JFrame {
    JFileChooser fc;
    FileOperations fileOps;
    
    /** Creates new form FileOperationsUI */
    public FileOperationsUI() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    FileOperationsUI(FileOperations fileOps) {
        this.fileOps = fileOps;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnSource = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnDestination = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        chkShowProgress = new javax.swing.JCheckBox();
        chkYesToAll = new javax.swing.JCheckBox();
        chkNameCollisionRename = new javax.swing.JCheckBox();
        chkConfirmDirCreation = new javax.swing.JCheckBox();
        chkFilesOnly = new javax.swing.JCheckBox();
        rbCopy = new javax.swing.JRadioButton();
        rbMove = new javax.swing.JRadioButton();
        rbRename = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtFieldSource = new javax.swing.JTextField();
        txtFieldDestination = new javax.swing.JTextField();
        btnFileOperation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Windows File Operations");
        setResizable(false);

        jLabel1.setText("Select Source File or Folder:");

        btnSource.setText("...");
        btnSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSourceActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Destination File or Folder:");

        btnDestination.setText("...");
        btnDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestinationActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Options"));

        chkShowProgress.setText("Show Progress Dialog Box");

        chkYesToAll.setText("Add \"Yes to All\" Button in the Confirmation Dialog");

        chkNameCollisionRename.setText("Resolve Name Collision when Destination File or Folder Already Exists");

        chkConfirmDirCreation.setText("Do Not Confirm New Folder Creation");

        chkFilesOnly.setText("Perform File Operation Only for Files, not Folders");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkFilesOnly)
                    .addComponent(chkConfirmDirCreation)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(chkYesToAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkShowProgress)
                        .addComponent(chkNameCollisionRename)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkShowProgress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkYesToAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkNameCollisionRename)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkConfirmDirCreation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkFilesOnly)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        buttonGroup1.add(rbCopy);
        rbCopy.setSelected(true);
        rbCopy.setText("Copy");

        buttonGroup1.add(rbMove);
        rbMove.setText("Move");

        buttonGroup1.add(rbRename);
        rbRename.setText("Rename");

        jLabel3.setText("Choose File Operation:");

        btnFileOperation.setText("Perform File Operation");
        btnFileOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileOperationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnFileOperation))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbCopy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbMove)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbRename))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFieldDestination)
                                            .addComponent(txtFieldSource, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSource, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDestination, 0, 0, Short.MAX_VALUE))))))))
                .addGap(18, 18, 18))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDestination, btnSource});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txtFieldSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSource))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(btnDestination)
                    .addComponent(txtFieldDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rbCopy)
                    .addComponent(jLabel3)
                    .addComponent(rbMove)
                    .addComponent(rbRename))
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFileOperation)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDestination, btnSource});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSourceActionPerformed
        txtFieldSource.setText(chooseFileFolder(fc));
    }//GEN-LAST:event_btnSourceActionPerformed

    private void btnFileOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileOperationActionPerformed
        int selectedCommand=0;
        if (rbCopy.isSelected())
            selectedCommand=0;
        else if (rbMove.isSelected())
            selectedCommand=1;
        else
            selectedCommand=2;
        
        fileOps.performFileOperation(selectedCommand);
        
    }//GEN-LAST:event_btnFileOperationActionPerformed

    private void btnDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestinationActionPerformed
        txtFieldDestination.setText(chooseFileFolder(fc));
    }//GEN-LAST:event_btnDestinationActionPerformed
    private String chooseFileFolder(JFileChooser fc) {
       String selectedPath = "";
       //Set up the file chooser.
       fc = new JFileChooser();

       fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
       fc.setApproveButtonText("Select");
       fc.setDialogTitle("Select a File or Folder");
        //Show it.
        int returnVal = fc.showDialog(this, null);
        
        //Process the results.
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            selectedPath = file.getPath();
        }
        //Reset the file chooser for the next time it's shown.
        fc.setSelectedFile(null);
        return selectedPath;
    }

    public static void main(String args[]) {
         try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FileOperationsUI().setVisible(true);
                }
            });
         } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDestination;
    private javax.swing.JButton btnFileOperation;
    private javax.swing.JButton btnSource;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JCheckBox chkConfirmDirCreation;
    public javax.swing.JCheckBox chkFilesOnly;
    public javax.swing.JCheckBox chkNameCollisionRename;
    public javax.swing.JCheckBox chkShowProgress;
    public javax.swing.JCheckBox chkYesToAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton rbCopy;
    public javax.swing.JRadioButton rbMove;
    public javax.swing.JRadioButton rbRename;
    public javax.swing.JTextField txtFieldDestination;
    public javax.swing.JTextField txtFieldSource;
    // End of variables declaration//GEN-END:variables
    
}
