/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test2 */

#ifndef _Included_Test2
#define _Included_Test2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test2
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Test2_hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
